version: '23'
services:
  manga.nest:
    image: ghcr.io/iufb/manga-nest/manga-nest:develop
    container_name: manga-nest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
      - ./uploads:/opt/app/uploads
