version: '3'
services:
  manga-nest:
    image: manga-nest:latest
    container_name: manga-nest
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - './.env:/opt/app/.env'
      - './uploads:/opt/app/uploads'
