version: '3'
services:
  manga.nest:
    image: docker.pkg.github.com/iufb/manga-nest/manga-nest:develop
    container_name: manga-nest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
